author: Some Body
title: My Personal Website
description: "A basic website on GitHub Pages"

markdown: kramdown
theme: minima

twitter_username: ???
github_username:  JeamayPalo
linkedin_username: jeamay-palo
